---
title: "Bego"
author: "Thomas Huet"
date: "11/12/2020"
header-includes:
  # - \usepackage{float}
  # - \floatplacement{figure}{H}  #make every figure with capti
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 10, fig.height = 10)
# opts_chunk$set(fig.width=12, fig.height=8)
library(kableExtra)
library(dplyr)
library(knitr)
library(magick)
library(leaflet)
library(RPostgreSQL)
library(rdrop2)
library(rgl)

GHimgs <- "https://github.com/zoometh/C14/tree/main/docs/imgs/"
# source("func/functions.R") # load/run ? function
# f.lflt.chef(getwd()) # create leaflet html map of the CdT
```

## *Roche de l'Homme aux bras en zigzag* (Zone IV, Groupe III, Roche 16D)

In the Arpette sector lies the *Roche de l'Homme aux bras en zigzag* 

```{r lf.HBZZ}
# load the lf map from img/CdT.html
# knitr::include_url("https://yihui.shinyapps.io/miniUI/")
# knitr::include_app(paste0(getwd(),"/img/m.html"), height = '600px')
htmltools::includeHTML(paste0(getwd(),"/img/ZIVGIIIR16D.html"))
```

## *Stèle du Chef de Tribu* (Zone VII, Groupe I, Roche 8)

In the vallées de Merveilles lies the unique stelae of the site, the so-called *Stèle du Chef de Tribu*


### Map 

```{r lf.CdT}
# load the lf map from img/CdT.html
# knitr::include_url("https://yihui.shinyapps.io/miniUI/")
# knitr::include_app(paste0(getwd(),"/img/m.html"), height = '600px')
htmltools::includeHTML(paste0(getwd(),"/img/CdT.html"))
```

This is really important..

## New paragraph

Near..
